import type { Metadata } from "next";
import {Jersey_10 } from "next/font/google";
import "./globals.css";

const jersey10 = Jersey_10({
    weight: "400",
    subsets: ["latin"],
    display: "swap",
});



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${jersey10.className}  antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
