import type { Metadata } from "next";
import { Jersey_10 } from "next/font/google";

const jersey_10 = Jersey_10({
  variable: "--font-jersey-10",
  weight: "400",
  style: "normal",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jersey_10.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
